<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * The V3 master keeps the platform and authentication catalog together.
     * All tenant-bound authentication records are protected by PostgreSQL RLS.
     */
    public function up(): void
    {
        $database = DB::connection('master_v3');

        $database->unprepared(<<<'SQL'
            CREATE EXTENSION IF NOT EXISTS pgcrypto;

            CREATE SCHEMA IF NOT EXISTS platform;
            CREATE SCHEMA IF NOT EXISTS auth;

            CREATE OR REPLACE FUNCTION auth.tenant_id() RETURNS uuid
            LANGUAGE plpgsql
            STABLE
            AS $$
            BEGIN
                RETURN nullif(current_setting('app.tenant_id', true), '')::uuid;
            EXCEPTION WHEN invalid_text_representation THEN
                RETURN NULL;
            END;
            $$;

            CREATE TABLE IF NOT EXISTS platform.tenants (
                id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
                legacy_id bigint GENERATED BY DEFAULT AS IDENTITY,
                ruc text NOT NULL UNIQUE,
                name text NOT NULL,
                synthetic boolean NOT NULL DEFAULT true
            );

            CREATE UNIQUE INDEX IF NOT EXISTS platform_tenants_legacy_id
                ON platform.tenants (legacy_id);

            CREATE TABLE IF NOT EXISTS auth.users (
                id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
                legacy_id bigint GENERATED BY DEFAULT AS IDENTITY,
                name text NOT NULL,
                email text,
                first_name text,
                last_name text,
                password_hash text NOT NULL,
                platform_admin boolean NOT NULL DEFAULT false,
                active boolean NOT NULL DEFAULT true
            );

            CREATE UNIQUE INDEX IF NOT EXISTS auth_users_legacy_id
                ON auth.users (legacy_id);
            CREATE UNIQUE INDEX IF NOT EXISTS auth_users_email_ci
                ON auth.users (lower(email))
                WHERE email IS NOT NULL;

            CREATE TABLE IF NOT EXISTS auth.tenant_memberships (
                tenant_id uuid NOT NULL REFERENCES platform.tenants(id),
                id uuid NOT NULL DEFAULT gen_random_uuid(),
                user_id uuid NOT NULL REFERENCES auth.users(id),
                active boolean NOT NULL DEFAULT true,
                authorization_version bigint NOT NULL DEFAULT 1,
                capabilities text[] NOT NULL DEFAULT '{}',
                PRIMARY KEY (tenant_id, id),
                UNIQUE (tenant_id, user_id),
                UNIQUE (tenant_id, id, user_id)
            );

            CREATE TABLE IF NOT EXISTS auth.sessions (
                token_hash text PRIMARY KEY,
                tenant_id uuid NOT NULL,
                user_id uuid NOT NULL REFERENCES auth.users(id),
                membership_id uuid NOT NULL,
                authorization_version bigint NOT NULL,
                expires_at timestamptz NOT NULL,
                FOREIGN KEY (tenant_id, membership_id)
                    REFERENCES auth.tenant_memberships(tenant_id, id),
                FOREIGN KEY (tenant_id, membership_id, user_id)
                    REFERENCES auth.tenant_memberships(tenant_id, id, user_id)
            );

            CREATE TABLE IF NOT EXISTS auth.login_attempts (
                address inet NOT NULL,
                minute timestamptz NOT NULL,
                attempts integer NOT NULL,
                PRIMARY KEY (address, minute)
            );

            ALTER TABLE auth.sessions ENABLE ROW LEVEL SECURITY;
            ALTER TABLE auth.sessions FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS tenant_isolation ON auth.sessions;
            CREATE POLICY tenant_isolation ON auth.sessions
                USING (tenant_id = auth.tenant_id())
                WITH CHECK (tenant_id = auth.tenant_id());

            ALTER TABLE auth.tenant_memberships ENABLE ROW LEVEL SECURITY;
            ALTER TABLE auth.tenant_memberships FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS tenant_isolation ON auth.tenant_memberships;
            CREATE POLICY tenant_isolation ON auth.tenant_memberships
                USING (tenant_id = auth.tenant_id())
                WITH CHECK (tenant_id = auth.tenant_id());

            CREATE OR REPLACE FUNCTION auth.resolve_session(token text)
            RETURNS TABLE(tenant_id uuid, user_id uuid, capabilities text[], platform_admin boolean)
            LANGUAGE sql
            SECURITY DEFINER
            SET search_path = pg_catalog
            AS $$
                SELECT s.tenant_id, s.user_id, m.capabilities, u.platform_admin
                FROM auth.sessions s
                JOIN auth.tenant_memberships m
                    ON m.tenant_id = s.tenant_id
                    AND m.id = s.membership_id
                    AND m.user_id = s.user_id
                JOIN auth.users u ON u.id = s.user_id
                WHERE s.token_hash = token
                    AND s.expires_at > now()
                    AND m.active
                    AND u.active
                    AND s.authorization_version = m.authorization_version
            $$;

            REVOKE ALL ON FUNCTION auth.resolve_session(text) FROM PUBLIC;
            SQL);
    }

    public function down(): void
    {
        $database = DB::connection('master_v3');

        $database->unprepared(<<<'SQL'
            DROP FUNCTION IF EXISTS auth.resolve_session(text);
            DROP FUNCTION IF EXISTS auth.tenant_id();
            DROP SCHEMA IF EXISTS auth CASCADE;
            DROP SCHEMA IF EXISTS platform CASCADE;
            SQL);
    }
};
