<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Tenant-bound additional info presets for invoice configuration. RLS enabled.
 */
return new class extends Migration
{
    public function up(): void
    {
        DB::connection('master_v3')->unprepared(<<<'SQL'
            CREATE TABLE IF NOT EXISTS fiscal.additional_info_presets(
                tenant_id uuid NOT NULL REFERENCES platform.tenants(id),
                id uuid NOT NULL DEFAULT gen_random_uuid(),
                legacy_id bigint GENERATED BY DEFAULT AS IDENTITY,
                code text NOT NULL,
                name text NOT NULL,
                default_value text,
                auto_apply boolean NOT NULL DEFAULT false,
                value_editable boolean NOT NULL DEFAULT true,
                is_required boolean NOT NULL DEFAULT false,
                is_active boolean NOT NULL DEFAULT true,
                sort_order integer NOT NULL DEFAULT 0,
                access_rules jsonb NOT NULL DEFAULT '[]'::jsonb,
                created_at timestamptz NOT NULL DEFAULT now(),
                updated_at timestamptz NOT NULL DEFAULT now(),
                PRIMARY KEY(tenant_id,id),
                UNIQUE(tenant_id,legacy_id),
                UNIQUE(tenant_id,code)
            );

            CREATE INDEX IF NOT EXISTS fiscal_additional_info_presets_active
                ON fiscal.additional_info_presets(tenant_id,is_active,sort_order,legacy_id);

            ALTER TABLE fiscal.additional_info_presets ENABLE ROW LEVEL SECURITY;
            ALTER TABLE fiscal.additional_info_presets FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS tenant_isolation ON fiscal.additional_info_presets;
            CREATE POLICY tenant_isolation ON fiscal.additional_info_presets
                USING (tenant_id = auth.tenant_id())
                WITH CHECK (tenant_id = auth.tenant_id());
            SQL);
    }

    public function down(): void
    {
        DB::connection('master_v3')->unprepared(<<<'SQL'
            DROP TABLE IF EXISTS fiscal.additional_info_presets CASCADE;
            SQL);
    }
};
