<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Tenant-bound declared payment conditions per document (SRI payment method, term, time unit). RLS enabled.
 */
return new class extends Migration
{
    public function up(): void
    {
        DB::connection('master_v3')->unprepared(<<<'SQL'
            CREATE TABLE IF NOT EXISTS fiscal.document_payments(
                tenant_id uuid NOT NULL,
                id uuid NOT NULL DEFAULT gen_random_uuid(),
                legacy_id bigint GENERATED BY DEFAULT AS IDENTITY,
                document_id uuid NOT NULL,
                position int NOT NULL CHECK(position > 0),
                payment_method_code text NOT NULL CHECK(payment_method_code ~ '^[0-9]{2}$'),
                total numeric(18,2) NOT NULL CHECK(total > 0),
                term int CHECK(term IS NULL OR term >= 0),
                time_unit text CHECK(time_unit IS NULL OR time_unit IN ('days','months','years')),
                due_date date,
                created_at timestamptz NOT NULL DEFAULT now(),
                PRIMARY KEY(tenant_id,id),
                UNIQUE(tenant_id,legacy_id),
                UNIQUE(tenant_id,document_id,position),
                FOREIGN KEY(tenant_id,document_id) REFERENCES fiscal.documents(tenant_id,id)
            );

            CREATE INDEX IF NOT EXISTS fiscal_document_payments_document
                ON fiscal.document_payments(tenant_id, document_id, position);

            ALTER TABLE fiscal.document_payments ENABLE ROW LEVEL SECURITY;
            ALTER TABLE fiscal.document_payments FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS tenant_isolation ON fiscal.document_payments;
            CREATE POLICY tenant_isolation ON fiscal.document_payments
                USING (tenant_id = auth.tenant_id())
                WITH CHECK (tenant_id = auth.tenant_id());
            SQL);
    }

    public function down(): void
    {
        DB::connection('master_v3')->unprepared(<<<'SQL'
            DROP TABLE IF EXISTS fiscal.document_payments CASCADE;
            SQL);
    }
};
