<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Tenant-bound received documents from external issuers. Consolidated with columns from 012 (legacy_id, document_type, fiscal_status, access_key, authorization_number, issued_at, original_received_document_id, reason, affects_transport). RLS enabled.
 */
return new class extends Migration
{
    public function up(): void
    {
        DB::connection('master_v3')->unprepared(<<<'SQL'
            CREATE TABLE IF NOT EXISTS fiscal.received_documents(
                tenant_id uuid NOT NULL,
                id uuid NOT NULL DEFAULT gen_random_uuid(),
                legacy_id bigint GENERATED BY DEFAULT AS IDENTITY,
                issuer_id uuid NOT NULL,
                issuer_snapshot jsonb NOT NULL,
                recipient_snapshot jsonb NOT NULL,
                reference text NOT NULL,
                operation_id uuid NOT NULL,
                total numeric(18,2) NOT NULL CHECK(total>=0),
                original_xml bytea NOT NULL,
                xml_sha256 text NOT NULL,
                document_type text NOT NULL DEFAULT 'invoice' CHECK(document_type IN ('invoice','credit_note','debit_note','other')),
                fiscal_status text NOT NULL DEFAULT 'imported' CHECK(fiscal_status IN ('draft','received','authorized','imported','rejected','cancelled')),
                access_key text,
                authorization_number text,
                issued_at timestamptz NOT NULL DEFAULT now(),
                original_received_document_id uuid,
                reason text,
                affects_transport boolean NOT NULL DEFAULT true,
                PRIMARY KEY(tenant_id,id),
                FOREIGN KEY(tenant_id,issuer_id) REFERENCES core.third_parties(tenant_id,id),
                FOREIGN KEY(tenant_id,operation_id) REFERENCES core.transport_operations(tenant_id,id),
                FOREIGN KEY(tenant_id,original_received_document_id) REFERENCES fiscal.received_documents(tenant_id,id),
                UNIQUE(tenant_id,issuer_id,reference),
                UNIQUE(tenant_id,legacy_id)
            );

            CREATE INDEX IF NOT EXISTS fiscal_received_documents_operation
                ON fiscal.received_documents(tenant_id, operation_id, document_type, issued_at DESC);

            ALTER TABLE fiscal.received_documents ENABLE ROW LEVEL SECURITY;
            ALTER TABLE fiscal.received_documents FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS tenant_isolation ON fiscal.received_documents;
            CREATE POLICY tenant_isolation ON fiscal.received_documents
                USING (tenant_id = auth.tenant_id())
                WITH CHECK (tenant_id = auth.tenant_id());
            SQL);
    }

    public function down(): void
    {
        DB::connection('master_v3')->unprepared(<<<'SQL'
            DROP TABLE IF EXISTS fiscal.received_documents CASCADE;
            SQL);
    }
};
