<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Tenant-bound carrier emission points with sequential counter. RLS enabled.
 */
return new class extends Migration
{
    public function up(): void
    {
        DB::connection('master_v3')->unprepared(<<<'SQL'
            CREATE TABLE IF NOT EXISTS core.carrier_emission_points(
                tenant_id uuid NOT NULL,
                id uuid NOT NULL DEFAULT gen_random_uuid(),
                legacy_id bigint GENERATED BY DEFAULT AS IDENTITY,
                establishment_id uuid NOT NULL,
                sri_code text NOT NULL CHECK(sri_code ~ '^[0-9]{3}$'),
                name text,
                next_sequential bigint NOT NULL DEFAULT 1 CHECK(next_sequential BETWEEN 1 AND 999999999),
                is_active boolean NOT NULL DEFAULT true,
                PRIMARY KEY(tenant_id,id),
                UNIQUE(tenant_id,establishment_id,sri_code),
                UNIQUE(tenant_id,legacy_id),
                FOREIGN KEY(tenant_id,establishment_id) REFERENCES core.carrier_establishments(tenant_id,id)
            );

            ALTER TABLE core.carrier_emission_points ENABLE ROW LEVEL SECURITY;
            ALTER TABLE core.carrier_emission_points FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS tenant_isolation ON core.carrier_emission_points;
            CREATE POLICY tenant_isolation ON core.carrier_emission_points
                USING (tenant_id = auth.tenant_id())
                WITH CHECK (tenant_id = auth.tenant_id());
            SQL);
    }

    public function down(): void
    {
        DB::connection('master_v3')->unprepared(<<<'SQL'
            DROP TABLE IF EXISTS core.carrier_emission_points CASCADE;
            SQL);
    }
};
