<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Tenant-bound product-to-IVA-type assignment (1:1). RLS enabled.
 */
return new class extends Migration
{
    public function up(): void
    {
        DB::connection('master_v3')->unprepared(<<<'SQL'
            CREATE TABLE IF NOT EXISTS core.product_taxes(
                tenant_id uuid NOT NULL,
                id bigint GENERATED BY DEFAULT AS IDENTITY,
                product_id uuid NOT NULL,
                sri_iva_type_id bigint NOT NULL,
                tax_name text NOT NULL,
                created_at timestamptz NOT NULL DEFAULT now(),
                PRIMARY KEY(tenant_id,id),
                FOREIGN KEY(tenant_id,product_id) REFERENCES core.products(tenant_id,id) ON DELETE CASCADE,
                FOREIGN KEY(tenant_id,sri_iva_type_id) REFERENCES core.sri_iva_types(tenant_id,id),
                UNIQUE(tenant_id,product_id)
            );

            ALTER TABLE core.product_taxes ENABLE ROW LEVEL SECURITY;
            ALTER TABLE core.product_taxes FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS tenant_isolation ON core.product_taxes;
            CREATE POLICY tenant_isolation ON core.product_taxes
                USING (tenant_id = auth.tenant_id())
                WITH CHECK (tenant_id = auth.tenant_id());
            SQL);
    }

    public function down(): void
    {
        DB::connection('master_v3')->unprepared(<<<'SQL'
            DROP TABLE IF EXISTS core.product_taxes CASCADE;
            SQL);
    }
};
