<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Tenant-bound carrier payment accounts with encrypted account numbers. RLS enabled.
 */
return new class extends Migration
{
    public function up(): void
    {
        DB::connection('master_v3')->unprepared(<<<'SQL'
            CREATE TABLE IF NOT EXISTS core.carrier_payment_accounts(
                tenant_id uuid NOT NULL,
                id uuid NOT NULL DEFAULT gen_random_uuid(),
                legacy_id bigint GENERATED BY DEFAULT AS IDENTITY,
                carrier_company_id uuid NOT NULL,
                account_holder_name text NOT NULL,
                account_holder_identification text NOT NULL,
                financial_institution text NOT NULL,
                account_type text NOT NULL CHECK(account_type IN ('savings','checking','other')),
                account_number_ciphertext text NOT NULL,
                account_number_last4 text NOT NULL CHECK(account_number_last4 ~ '^[0-9]{4}$'),
                currency text NOT NULL DEFAULT 'USD' CHECK(currency='USD'),
                verification_status text NOT NULL DEFAULT 'pending' CHECK(verification_status IN ('pending','verified','blocked')),
                is_primary boolean NOT NULL DEFAULT true,
                is_active boolean NOT NULL DEFAULT true,
                created_by uuid,
                updated_by uuid,
                created_at timestamptz NOT NULL DEFAULT now(),
                updated_at timestamptz NOT NULL DEFAULT now(),
                PRIMARY KEY(tenant_id,id),
                UNIQUE(tenant_id,legacy_id),
                FOREIGN KEY(tenant_id,carrier_company_id) REFERENCES core.carrier_companies(tenant_id,id),
                FOREIGN KEY(created_by) REFERENCES auth.users(id),
                FOREIGN KEY(updated_by) REFERENCES auth.users(id),
                CHECK(length(trim(account_holder_name)) >= 2),
                CHECK(length(trim(account_holder_identification)) >= 5),
                CHECK(length(trim(financial_institution)) >= 2)
            );

            CREATE UNIQUE INDEX IF NOT EXISTS core_carrier_payment_accounts_primary
                ON core.carrier_payment_accounts(tenant_id, carrier_company_id)
                WHERE is_primary AND is_active;

            CREATE INDEX IF NOT EXISTS core_carrier_payment_accounts_carrier
                ON core.carrier_payment_accounts(tenant_id, carrier_company_id, is_active, updated_at DESC);

            ALTER TABLE core.carrier_payment_accounts ENABLE ROW LEVEL SECURITY;
            ALTER TABLE core.carrier_payment_accounts FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS tenant_isolation ON core.carrier_payment_accounts;
            CREATE POLICY tenant_isolation ON core.carrier_payment_accounts
                USING (tenant_id = auth.tenant_id())
                WITH CHECK (tenant_id = auth.tenant_id());
            SQL);
    }

    public function down(): void
    {
        DB::connection('master_v3')->unprepared(<<<'SQL'
            DROP TABLE IF EXISTS core.carrier_payment_accounts CASCADE;
            SQL);
    }
};
