<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Tenant-bound product tax assignments with percentage and SRI code. RLS enabled.
 */
return new class extends Migration
{
    public function up(): void
    {
        DB::connection('master_v3')->unprepared(<<<'SQL'
            CREATE TABLE IF NOT EXISTS core.product_tax_assignments(
                tenant_id uuid NOT NULL REFERENCES platform.tenants(id),
                id uuid NOT NULL DEFAULT gen_random_uuid(),
                legacy_id bigint GENERATED BY DEFAULT AS IDENTITY,
                product_id uuid NOT NULL,
                sri_iva_type_id bigint NOT NULL,
                tax_name text NOT NULL,
                percentage numeric(8,6) NOT NULL CHECK(percentage >= 0 AND percentage <= 100),
                sri_code text NOT NULL,
                is_active boolean NOT NULL DEFAULT true,
                created_at timestamptz NOT NULL DEFAULT now(),
                updated_at timestamptz NOT NULL DEFAULT now(),
                PRIMARY KEY(tenant_id,id),
                UNIQUE(tenant_id,legacy_id),
                UNIQUE(tenant_id,product_id,sri_iva_type_id),
                FOREIGN KEY(tenant_id,product_id) REFERENCES core.products(tenant_id,id)
            );

            CREATE INDEX IF NOT EXISTS product_tax_assignments_active
                ON core.product_tax_assignments(tenant_id,product_id,is_active);

            ALTER TABLE core.product_tax_assignments ENABLE ROW LEVEL SECURITY;
            ALTER TABLE core.product_tax_assignments FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS tenant_isolation ON core.product_tax_assignments;
            CREATE POLICY tenant_isolation ON core.product_tax_assignments
                USING (tenant_id = auth.tenant_id())
                WITH CHECK (tenant_id = auth.tenant_id());
            SQL);
    }

    public function down(): void
    {
        DB::connection('master_v3')->unprepared(<<<'SQL'
            DROP TABLE IF EXISTS core.product_tax_assignments CASCADE;
            SQL);
    }
};
