<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::connection('master_v3')->statement(<<<'SQL'
            ALTER TABLE core.establishments
                ADD COLUMN IF NOT EXISTS legacy_id bigint GENERATED BY DEFAULT AS IDENTITY,
                ADD COLUMN IF NOT EXISTS branch_code text,
                ADD COLUMN IF NOT EXISTS address text,
                ADD COLUMN IF NOT EXISTS phone text,
                ADD COLUMN IF NOT EXISTS email text,
                ADD COLUMN IF NOT EXISTS city_id bigint,
                ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT true;
        SQL);

        DB::connection('master_v3')->statement(<<<'SQL'
            CREATE UNIQUE INDEX IF NOT EXISTS core_establishments_legacy_id
                ON core.establishments (tenant_id, legacy_id);
        SQL);
    }

    public function down(): void
    {
        DB::statement('DROP INDEX IF EXISTS core_establishments_legacy_id');

        DB::connection('master_v3')->statement(<<<'SQL'
            ALTER TABLE core.establishments
                DROP COLUMN IF EXISTS is_active,
                DROP COLUMN IF EXISTS city_id,
                DROP COLUMN IF EXISTS email,
                DROP COLUMN IF EXISTS phone,
                DROP COLUMN IF EXISTS address,
                DROP COLUMN IF EXISTS branch_code,
                DROP COLUMN IF EXISTS legacy_id;
        SQL);
    }
};
