<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Tenant-bound SRI IVA type catalog. RLS enabled.
 */
return new class extends Migration
{
    public function up(): void
    {
        DB::connection('master_v3')->unprepared(<<<'SQL'
            CREATE TABLE IF NOT EXISTS core.sri_iva_types(
                tenant_id uuid NOT NULL,
                id bigint GENERATED BY DEFAULT AS IDENTITY,
                name text NOT NULL,
                percentage numeric(5,2) NOT NULL DEFAULT 0,
                sri_code text NOT NULL,
                is_active boolean NOT NULL DEFAULT true,
                PRIMARY KEY(tenant_id,id),
                FOREIGN KEY(tenant_id) REFERENCES platform.tenants(id)
            );

            ALTER TABLE core.sri_iva_types ENABLE ROW LEVEL SECURITY;
            ALTER TABLE core.sri_iva_types FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS tenant_isolation ON core.sri_iva_types;
            CREATE POLICY tenant_isolation ON core.sri_iva_types
                USING (tenant_id = auth.tenant_id())
                WITH CHECK (tenant_id = auth.tenant_id());
            SQL);
    }

    public function down(): void
    {
        DB::connection('master_v3')->unprepared(<<<'SQL'
            DROP TABLE IF EXISTS core.sri_iva_types CASCADE;
            SQL);
    }
};
