<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Add missing columns to core.products to match ArtraFiscalBackEnd schema.
 *
 * Adds: legacy_id (bigint IDENTITY + unique index), barcode, auxiliary_code,
 * other_code, description, type (with CHECK), is_active, sri_principal_code.
 * Creates a trigger to auto-generate sri_principal_code as 'P' || legacy_id.
 */
return new class extends Migration
{
    public function up(): void
    {
        DB::connection('master_v3')->unprepared(<<<'SQL'
            ALTER TABLE core.products
                ADD COLUMN IF NOT EXISTS legacy_id bigint GENERATED BY DEFAULT AS IDENTITY;

            CREATE UNIQUE INDEX IF NOT EXISTS core_products_legacy_id
                ON core.products (tenant_id, legacy_id);

            ALTER TABLE core.products
                ADD COLUMN IF NOT EXISTS barcode text,
                ADD COLUMN IF NOT EXISTS auxiliary_code text,
                ADD COLUMN IF NOT EXISTS other_code text,
                ADD COLUMN IF NOT EXISTS description text,
                ADD COLUMN IF NOT EXISTS type text NOT NULL DEFAULT 'product',
                ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT true,
                ADD COLUMN IF NOT EXISTS sri_principal_code varchar(25);

            DO $$ BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint
                    WHERE conname = 'core_products_type_check'
                      AND conrelid = 'core.products'::regclass
                ) THEN
                    ALTER TABLE core.products
                        ADD CONSTRAINT core_products_type_check CHECK (type IN ('product', 'service'));
                END IF;
            END $$;

            CREATE OR REPLACE FUNCTION core.ensure_sri_principal_code()
            RETURNS trigger
            LANGUAGE plpgsql
            AS $$
            BEGIN
                IF TG_OP = 'UPDATE' AND NEW.sri_principal_code IS DISTINCT FROM OLD.sri_principal_code THEN
                    RAISE EXCEPTION 'sri_principal_code is immutable for a consolidated product';
                END IF;
                IF NEW.sri_principal_code IS NULL OR btrim(NEW.sri_principal_code) = '' THEN
                    IF NEW.legacy_id IS NULL THEN
                        NEW.legacy_id := nextval(pg_get_serial_sequence('core.products', 'legacy_id'));
                    END IF;
                    NEW.sri_principal_code := 'P' || NEW.legacy_id::text;
                END IF;
                RETURN NEW;
            END;
            $$;

            DROP TRIGGER IF EXISTS ensure_sri_principal_code ON core.products;
            CREATE TRIGGER ensure_sri_principal_code
                BEFORE INSERT OR UPDATE OF sri_principal_code ON core.products
                FOR EACH ROW EXECUTE FUNCTION core.ensure_sri_principal_code();
            SQL);
    }

    public function down(): void
    {
        DB::connection('master_v3')->unprepared(<<<'SQL'
            DROP TRIGGER IF EXISTS ensure_sri_principal_code ON core.products;
            DROP FUNCTION IF EXISTS core.ensure_sri_principal_code();
            ALTER TABLE core.products
                DROP CONSTRAINT IF EXISTS core_products_type_check;
            DROP INDEX IF EXISTS core_products_legacy_id;
            ALTER TABLE core.products
                DROP COLUMN IF EXISTS sri_principal_code,
                DROP COLUMN IF EXISTS is_active,
                DROP COLUMN IF EXISTS type,
                DROP COLUMN IF EXISTS description,
                DROP COLUMN IF EXISTS other_code,
                DROP COLUMN IF EXISTS auxiliary_code,
                DROP COLUMN IF EXISTS barcode,
                DROP COLUMN IF EXISTS legacy_id;
            SQL);
    }
};
