<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Tenant-bound SRI IVA percentages. RLS enabled.
 * Each percentage belongs to a core.sri_iva_types row and tracks validity by date range.
 */
return new class extends Migration
{
    public function up(): void
    {
        DB::connection('master_v3')->unprepared(<<<'SQL'
            CREATE TABLE IF NOT EXISTS core.sri_iva_percentages(
                tenant_id uuid NOT NULL,
                id bigint GENERATED BY DEFAULT AS IDENTITY,
                sri_iva_type_id bigint NOT NULL,
                percentage numeric(5,2) NOT NULL,
                start_date date NOT NULL,
                end_date date,
                code text NOT NULL,
                is_active boolean NOT NULL DEFAULT true,
                PRIMARY KEY(tenant_id,id),
                FOREIGN KEY(tenant_id, sri_iva_type_id)
                    REFERENCES core.sri_iva_types(tenant_id, id)
                    ON DELETE CASCADE
            );

            ALTER TABLE core.sri_iva_percentages ENABLE ROW LEVEL SECURITY;
            ALTER TABLE core.sri_iva_percentages FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS tenant_isolation ON core.sri_iva_percentages;
            CREATE POLICY tenant_isolation ON core.sri_iva_percentages
                USING (tenant_id = auth.tenant_id())
                WITH CHECK (tenant_id = auth.tenant_id());
            SQL);
    }

    public function down(): void
    {
        DB::connection('master_v3')->unprepared(<<<'SQL'
            DROP TABLE IF EXISTS core.sri_iva_percentages CASCADE;
            SQL);
    }
};
