<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Tenant-bound transport operations linking customers and carriers. RLS enabled.
 */
return new class extends Migration
{
    public function up(): void
    {
        DB::connection('master_v3')->unprepared(<<<'SQL'
            CREATE TABLE IF NOT EXISTS core.transport_operations(
                tenant_id uuid NOT NULL REFERENCES platform.tenants(id),
                id uuid NOT NULL DEFAULT gen_random_uuid(),
                legacy_id bigint GENERATED BY DEFAULT AS IDENTITY,
                customer_id uuid,
                carrier_company_id uuid,
                service_date date NOT NULL DEFAULT CURRENT_DATE,
                reference text,
                notes text,
                status text NOT NULL DEFAULT 'open' CHECK(status IN ('open','partially_settled','settled','blocked','cancelled')),
                issuer_snapshot jsonb,
                created_by uuid,
                created_at timestamptz NOT NULL DEFAULT now(),
                updated_at timestamptz NOT NULL DEFAULT now(),
                PRIMARY KEY(tenant_id,id),
                UNIQUE(tenant_id,legacy_id),
                FOREIGN KEY(tenant_id,customer_id) REFERENCES core.third_parties(tenant_id,id),
                FOREIGN KEY(tenant_id,carrier_company_id) REFERENCES core.carrier_companies(tenant_id,id),
                FOREIGN KEY(created_by) REFERENCES auth.users(id)
            );

            CREATE INDEX IF NOT EXISTS core_transport_operations_carrier_status
                ON core.transport_operations(tenant_id, carrier_company_id, status, service_date DESC);

            ALTER TABLE core.transport_operations ENABLE ROW LEVEL SECURITY;
            ALTER TABLE core.transport_operations FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS tenant_isolation ON core.transport_operations;
            CREATE POLICY tenant_isolation ON core.transport_operations
                USING (tenant_id = auth.tenant_id())
                WITH CHECK (tenant_id = auth.tenant_id());
            SQL);
    }

    public function down(): void
    {
        DB::connection('master_v3')->unprepared(<<<'SQL'
            DROP TABLE IF EXISTS core.transport_operations CASCADE;
            SQL);
    }
};
