<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::connection('master_v3')->statement(<<<'SQL'
            ALTER TABLE core.emission_points
                ADD COLUMN IF NOT EXISTS legacy_id bigint GENERATED BY DEFAULT AS IDENTITY,
                ADD COLUMN IF NOT EXISTS name text,
                ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT true,
                ADD COLUMN IF NOT EXISTS is_default boolean NOT NULL DEFAULT false,
                ADD COLUMN IF NOT EXISTS has_tax_validity boolean NOT NULL DEFAULT true;
        SQL);

        DB::connection('master_v3')->statement(<<<'SQL'
            CREATE UNIQUE INDEX IF NOT EXISTS core_emission_points_legacy_id
                ON core.emission_points (tenant_id, legacy_id);
        SQL);
    }

    public function down(): void
    {
        DB::statement('DROP INDEX IF EXISTS core_emission_points_legacy_id');

        DB::connection('master_v3')->statement(<<<'SQL'
            ALTER TABLE core.emission_points
                DROP COLUMN IF EXISTS has_tax_validity,
                DROP COLUMN IF EXISTS is_default,
                DROP COLUMN IF EXISTS is_active,
                DROP COLUMN IF EXISTS name,
                DROP COLUMN IF EXISTS legacy_id;
        SQL);
    }
};
