<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::connection('master_v3')->statement(<<<'SQL'
            ALTER TABLE core.vehicles
                ADD COLUMN IF NOT EXISTS legacy_id bigint GENERATED BY DEFAULT AS IDENTITY;
        SQL);

        DB::connection('master_v3')->statement(<<<'SQL'
            CREATE UNIQUE INDEX IF NOT EXISTS core_vehicles_legacy_id
                ON core.vehicles (tenant_id, legacy_id);
        SQL);
    }

    public function down(): void
    {
        DB::statement('DROP INDEX IF EXISTS core_vehicles_legacy_id');

        DB::connection('master_v3')->statement(<<<'SQL'
            ALTER TABLE core.vehicles
                DROP COLUMN IF EXISTS legacy_id;
        SQL);
    }
};
