<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Tenant-bound carrier establishments (SRI 3-digit code). RLS enabled.
 */
return new class extends Migration
{
    public function up(): void
    {
        DB::connection('master_v3')->unprepared(<<<'SQL'
            CREATE TABLE IF NOT EXISTS core.carrier_establishments(
                tenant_id uuid NOT NULL,
                id uuid NOT NULL DEFAULT gen_random_uuid(),
                legacy_id bigint GENERATED BY DEFAULT AS IDENTITY,
                carrier_company_id uuid NOT NULL,
                sri_code text NOT NULL CHECK(sri_code ~ '^[0-9]{3}$'),
                name text NOT NULL,
                address text,
                phone text,
                email text,
                city_id bigint,
                is_active boolean NOT NULL DEFAULT true,
                created_at timestamptz NOT NULL DEFAULT now(),
                updated_at timestamptz NOT NULL DEFAULT now(),
                PRIMARY KEY(tenant_id,id),
                UNIQUE(tenant_id,carrier_company_id,sri_code),
                UNIQUE(tenant_id,legacy_id),
                FOREIGN KEY(tenant_id,carrier_company_id) REFERENCES core.carrier_companies(tenant_id,id)
            );

            ALTER TABLE core.carrier_establishments ENABLE ROW LEVEL SECURITY;
            ALTER TABLE core.carrier_establishments FORCE ROW LEVEL SECURITY;
            DROP POLICY IF EXISTS tenant_isolation ON core.carrier_establishments;
            CREATE POLICY tenant_isolation ON core.carrier_establishments
                USING (tenant_id = auth.tenant_id())
                WITH CHECK (tenant_id = auth.tenant_id());
            SQL);
    }

    public function down(): void
    {
        DB::connection('master_v3')->unprepared(<<<'SQL'
            DROP TABLE IF EXISTS core.carrier_establishments CASCADE;
            SQL);
    }
};
