<?php

namespace App\Context\V1\Invoice\Application\DTOs;

class InvoiceDTO
{
    public function __construct(
        public ?int $id = null,
        public ?int $carrier_id = null,
        public ?string $environment = '1',
        public ?string $emission_type = '1',
        public ?string $ruc = null,
        public ?string $legal_name = null,
        public ?string $tradename = null,
        public ?string $access_key = null,
        public ?string $document_code = '01',
        public ?string $establishment = null,
        public ?string $emission_point = null,
        public ?string $sequential = null,
        public ?string $matrix_address = null,
        public ?string $issue_date = null,
        public ?string $establishment_address = null,
        public string $accounting_required = 'NO',
        public ?string $buyer_identification_type = null,
        public ?string $buyer_name = null,
        public ?string $buyer_identification = null,
        public ?string $buyer_address = null,
        public ?string $buyer_phone = null,
        public ?string $buyer_email = null,
        public float $subtotal = 0,
        public float $discount = 0,
        public float $tax_base = 0,
        public float $tax = 0,
        public float $tip = 0,
        public float $total = 0,
        public string $currency = 'DOLAR',
        public ?string $plate = null,
        public string $status = 'PENDIENTE',
        public array $items = [],
        public array $taxes = [],
        public array $payments = [],
        public array $additional_info = [],
    ) {}

    public static function fromArray(array $data): self
    {
        return new self(
            id: $data['id'] ?? null,
            carrier_id: $data['carrier_id'] ?? null,
            environment: $data['environment'] ?? '1',
            emission_type: $data['emission_type'] ?? '1',
            ruc: $data['ruc'] ?? null,
            legal_name: $data['legal_name'] ?? null,
            tradename: $data['tradename'] ?? null,
            access_key: $data['access_key'] ?? null,
            document_code: $data['document_code'] ?? '01',
            establishment: $data['establishment'] ?? null,
            emission_point: $data['emission_point'] ?? null,
            sequential: $data['sequential'] ?? null,
            matrix_address: $data['matrix_address'] ?? null,
            issue_date: $data['issue_date'] ?? null,
            establishment_address: $data['establishment_address'] ?? null,
            accounting_required: $data['accounting_required'] ?? 'NO',
            buyer_identification_type: $data['buyer_identification_type'] ?? null,
            buyer_name: $data['buyer_name'] ?? null,
            buyer_identification: $data['buyer_identification'] ?? null,
            buyer_address: $data['buyer_address'] ?? null,
            buyer_phone: $data['buyer_phone'] ?? null,
            buyer_email: $data['buyer_email'] ?? null,
            total_without_taxes: $data['total_without_taxes'] ?? 0,
            total_discount: $data['total_discount'] ?? 0,
            tip: $data['tip'] ?? 0,
            total_amount: $data['total_amount'] ?? 0,
            currency: $data['currency'] ?? 'DOLAR',
            plate: $data['plate'] ?? null,
            status: $data['status'] ?? 'PENDIENTE',
            items: $data['items'] ?? [],
            taxes: $data['taxes'] ?? [],
            payments: $data['payments'] ?? [],
            additional_info: $data['additional_info'] ?? [],
        );
    }

    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'carrier_id' => $this->carrier_id,
            'environment' => $this->environment,
            'emission_type' => $this->emission_type,
            'ruc' => $this->ruc,
            'legal_name' => $this->legal_name,
            'tradename' => $this->tradename,
            'access_key' => $this->access_key,
            'document_code' => $this->document_code,
            'establishment' => $this->establishment,
            'emission_point' => $this->emission_point,
            'sequential' => $this->sequential,
            'matrix_address' => $this->matrix_address,
            'issue_date' => $this->issue_date,
            'establishment_address' => $this->establishment_address,
            'accounting_required' => $this->accounting_required,
            'buyer_identification_type' => $this->buyer_identification_type,
            'buyer_name' => $this->buyer_name,
            'buyer_identification' => $this->buyer_identification,
            'buyer_address' => $this->buyer_address,
            'buyer_phone' => $this->buyer_phone,
            'buyer_email' => $this->buyer_email,
            'total_without_taxes' => $this->total_without_taxes,
            'total_discount' => $this->total_discount,
            'tip' => $this->tip,
            'total_amount' => $this->total_amount,
            'currency' => $this->currency,
            'plate' => $this->plate,
            'status' => $this->status,
            'items' => $this->items,
            'taxes' => $this->taxes,
            'payments' => $this->payments,
            'additional_info' => $this->additional_info,
        ];
    }
}
