<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::connection('master_v3')->unprepared(<<<'SQL'
            ALTER TABLE auth.users
                ADD COLUMN IF NOT EXISTS mfa_secret text,
                ADD COLUMN IF NOT EXISTS mfa_enabled boolean NOT NULL DEFAULT false,
                ADD COLUMN IF NOT EXISTS mfa_confirmed_at timestamptz;

            ALTER TABLE auth.sessions
                ADD COLUMN IF NOT EXISTS legacy_id bigint GENERATED BY DEFAULT AS IDENTITY,
                ADD COLUMN IF NOT EXISTS device_label text,
                ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now(),
                ADD COLUMN IF NOT EXISTS last_used_at timestamptz;

            CREATE UNIQUE INDEX IF NOT EXISTS auth_sessions_legacy_id
                ON auth.sessions (legacy_id);

            CREATE TABLE IF NOT EXISTS auth.user_preferences (
                user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
                preferences jsonb NOT NULL DEFAULT '{}'::jsonb,
                updated_at timestamptz NOT NULL DEFAULT now()
            );
            SQL);
    }

    public function down(): void
    {
        DB::connection('master_v3')->unprepared(<<<'SQL'
            DROP TABLE IF EXISTS auth.user_preferences;
            DROP INDEX IF EXISTS auth_sessions_legacy_id;
            ALTER TABLE auth.sessions
                DROP COLUMN IF EXISTS last_used_at,
                DROP COLUMN IF EXISTS created_at,
                DROP COLUMN IF EXISTS device_label,
                DROP COLUMN IF EXISTS legacy_id;
            ALTER TABLE auth.users
                DROP COLUMN IF EXISTS mfa_confirmed_at,
                DROP COLUMN IF EXISTS mfa_enabled,
                DROP COLUMN IF EXISTS mfa_secret;
            SQL);
    }
};
